project:
  type: website
  output-dir: docs

website:
  title: "Juan Hernández Guizar"
  navbar:
    left:
      - href: index.qmd
        text: '<i class="bi bi-house"></i> Home'
      - href: Resume.qmd
        text: '<i class="bi bi-newspaper"></i> Resume'
      - href: portfolio.qmd
        text: '<i class="bi bi-bar-chart"></i> Portfolio'

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    includes:
      in-header: bootstrap-icons.html
    # code-overflow: wrap   # fuerza el ‹wrap› en TODO el HTML
    code-width: 80  # 80 caracteres antes de envolver

format-options:
  editor:
    format-on-save: false