project:
  type: website
  output-dir: docs

website:
  title: "Juan Hernández Guizar"
  navbar:
    left:
      - href: index.qmd
        text: '<i class="bi bi-house"></i> Home'
      - href: Resume.qmd
        text: '<i class="bi bi-newspaper"></i> Resume'
      - href: blog.qmd
        text: '<i class="bi bi-bar-chart"></i> Portfolio'
      - text: "YouTube Channel"   # NUEVO botón "YouTube Channel"
        icon: youtube            # Ícono de YouTube (Bootstrap Icons)
        href: https://www.youtube.com/@CreaCircuitos   # Enlace a tu canal de YouTube
      - text: "Spotify Group Project"   # NUEVO botón "Spotify Project"
        icon: spotify            # Ícono de Spotify (Bootstrap Icons)
        href: https://rsm-aburda.github.io/MGTA-452-Final-Project/index.html   # Enlace al proyecto de Spotify

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    includes:
      in-header: bootstrap-icons.html
    # code-overflow: wrap   # fuerza el ‹wrap› en TODO el HTML
    code-width: 80  # 80 caracteres antes de envolver

format-options:
  editor:
    format-on-save: false